### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by chart21** [eceisik/BARFED#1]
Unfortunately, there are multiple errors after I create a Conda environment as specified in the Readme and run the scripts.

For instance:

```
from fl_utils import distribute_data as dd
  File "/home/christopher/BARFED/fl_utils/distribute_data.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

There are multiple modules that are affected. The missing modules can also not be installed manually with pip. 

Could you maybe set up the project in a clean environment and check if the install instructions from the Readme work for you?

**Comment by eceisik** [comment]
I see "requests" in the yml file.  I think that there was a problem while you were creating the environment. Which packages are listed after you type "conda list", could you please check it?

**Comment by chart21** [comment]
I just set up everything on a fresh ubuntu instance and everything worked fine. Thanks!
